### PR TITLE
Add device names / folder labels

### PR DESCRIPTION
**Pull request by shish**
Rather than
```
Device JA1LWTV-ZMMLQME-CJGO3VV-9FRG36T-EDWIILZ-EU6TMNK-EDHMXKN-ZYXWCAL hasn't synced in 24 hours
```
I'd like to see
```
Sunflower (Mom's backup laptop) hasn't synced in 24 hours
```
This PR makes that possible :)

I am slightly worried that I'm bad at golang and I've missed a cleaner way to do this though...

### CODE REVIEW

**Review by ojarva — APPROVED** [review]
Looks good, thanks!

**Comment by ojarva** [comment]
You'll need to rebase to master, though, as there's a merge conflict.

**Comment by shish** [comment]
Derp, somehow managed to push my original branch-of-a-branch instead of the cleaner version - should be fixed now ^^;

**Comment by shish** [comment]
(pushed the clean version now)

**Comment by shish** [comment]
In case somebody ends up here from google thinking "How do I use this?", writing down my query for the record:
```
from(bucket: "telegraf/autogen")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "syncthing_device")
  |> filter(fn: (r) => r["_field"] == "last_seen")
  |> group(columns: ["device_name"])
  |> map(fn: (r) => ({
    r with
    _value: (int(v: r._time) / int(v: 1000000000) - int(v: r._value)),
  }))
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

**Pull request merged**
