### PR TITLE
remove string fields, telegraf counts them as syntax error??

### PR DESCRIPTION
**Pull request by shish**
Using the code as-is, telegraf reports a syntax error, and throws away all of the data. After removing the string fields, everything else works fine. I'm not sure if string fields are actually supported and we're just using the wrong syntax, but I wasn't interested in those so removing them was the easiest way to get things working :)

### CODE REVIEW

**Comment by ojarva** [comment]
Hmm that's curious, this was working fine on my setup. I'll need to verify that. Maybe a quoting issue?

**Comment by shish** [comment]
In case it happens to be version specific, I'm on `Telegraf 1.19.1 (git: HEAD 9f8be047)`. If I'm reading the logs correctly, telegraf is rejecting the input before it reaches influx, but influx is v2.0 if that makes any difference.

**Comment by shish** [comment]
The specific error is:

```
Aug 26 13:39:21 chai telegraf[3071107]: 2021-08-26T13:39:21Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 21:152: "syncthing_connection,client_id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX connected=1,paused=0,in_bytes=4139,out_bytes=4513,type=tcp-client"
```

**Comment by ojarva** [comment]
It seems the latest version never got deployed to my system :man_facepalming: Which explains why I thought this is working just fine.

**Pull request merged**
